export interface Tool {
  id: string;
  name: string;
  description: string;
  category: string;
  subcategory?: string;
  url: string;
  logo?: string;
  pricing: 'free' | 'freemium' | 'paid' | 'enterprise';
  rating?: number; // 1-5
  review?: string;
  tags: string[];
  hasAPI?: boolean;
  used: boolean; // Have I actually used it
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  description: string;
  color: string;
}

export const categories: Category[] = [
  {
    id: 'coding-ide',
    name: 'AI Coding IDEs',
    icon: '💻',
    description: 'AI-powered code editors and IDEs',
    color: '#00e5ff',
  },
  {
    id: 'coding-cli',
    name: 'Terminal Agents',
    icon: '⌨️',
    description: 'CLI-based coding agents and assistants',
    color: '#00ff41',
  },
  {
    id: 'llm',
    name: 'Language Models',
    icon: '🧠',
    description: 'Chat interfaces and LLM platforms',
    color: '#ff00ff',
  },
  {
    id: 'video',
    name: 'Video Creation',
    icon: '🎬',
    description: 'AI video generation tools',
    color: '#ff6b6b',
  },
  {
    id: 'image',
    name: 'Image Generation',
    icon: '🎨',
    description: 'AI image creation and editing',
    color: '#ffd93d',
  },
  {
    id: 'voice',
    name: 'Voice & Audio',
    icon: '🎙️',
    description: 'Text-to-speech, voice cloning, transcription',
    color: '#4d96ff',
  },
  {
    id: 'music',
    name: 'Music Creation',
    icon: '🎵',
    description: 'AI music and audio generation',
    color: '#9b59b6',
  },
  {
    id: 'design',
    name: 'UX & Design',
    icon: '✏️',
    description: 'AI-powered design tools',
    color: '#e74c3c',
  },
  {
    id: 'api',
    name: 'APIs & Infrastructure',
    icon: '🔌',
    description: 'AI APIs and developer platforms',
    color: '#1abc9c',
  },
  {
    id: 'research',
    name: 'Research & Search',
    icon: '🔍',
    description: 'AI-powered search and research tools',
    color: '#f39c12',
  },
  {
    id: 'deploy',
    name: 'Deploy & Host',
    icon: '🚀',
    description: 'Deployment and hosting platforms',
    color: '#3498db',
  },
];

export const tools: Tool[] = [
  // === CODING IDEs ===
  {
    id: 'cursor',
    name: 'Cursor',
    description: 'AI-first code editor built on VS Code. Cmd+K to edit, chat with your codebase.',
    category: 'coding-ide',
    url: 'https://cursor.sh',
    pricing: 'freemium',
    rating: 5,
    review: 'The best AI coding IDE. Period. This is what I use daily.',
    tags: ['editor', 'vscode', 'claude', 'gpt'],
    used: true,
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    description: 'Codeium\'s AI IDE with Cascade for multi-file edits.',
    category: 'coding-ide',
    url: 'https://codeium.com/windsurf',
    pricing: 'freemium',
    tags: ['editor', 'codeium'],
    used: true,
  },
  {
    id: 'vscode',
    name: 'VS Code + Copilot',
    description: 'Classic VS Code with GitHub Copilot extension.',
    category: 'coding-ide',
    url: 'https://code.visualstudio.com',
    pricing: 'freemium',
    tags: ['editor', 'microsoft', 'copilot'],
    used: true,
  },
  {
    id: 'zed',
    name: 'Zed',
    description: 'Fast, multiplayer code editor with AI assistant built-in.',
    category: 'coding-ide',
    url: 'https://zed.dev',
    pricing: 'free',
    tags: ['editor', 'fast', 'rust'],
    used: false,
  },

  // === TERMINAL CODING AGENTS ===
  {
    id: 'claude-code',
    name: 'Claude Code',
    description: 'Anthropic\'s CLI coding agent. Agentic coding in the terminal.',
    category: 'coding-cli',
    url: 'https://docs.anthropic.com/en/docs/claude-code',
    pricing: 'paid',
    rating: 5,
    review: 'What Pinky runs on. Agentic coding at its finest.',
    tags: ['cli', 'anthropic', 'agent'],
    used: true,
  },
  {
    id: 'codex-cli',
    name: 'Codex CLI',
    description: 'OpenAI\'s terminal coding agent.',
    category: 'coding-cli',
    url: 'https://github.com/openai/codex-cli',
    pricing: 'paid',
    tags: ['cli', 'openai', 'agent'],
    used: true,
  },
  {
    id: 'gemini-cli',
    name: 'Gemini CLI',
    description: 'Google\'s Gemini in the terminal.',
    category: 'coding-cli',
    url: 'https://github.com/google-gemini/gemini-cli',
    pricing: 'freemium',
    tags: ['cli', 'google', 'gemini'],
    used: true,
  },
  {
    id: 'opencode',
    name: 'OpenCode',
    description: 'Open source terminal coding agent.',
    category: 'coding-cli',
    url: 'https://github.com/opencode-ai/opencode',
    pricing: 'free',
    tags: ['cli', 'opensource'],
    used: false,
  },
  {
    id: 'aider',
    name: 'Aider',
    description: 'AI pair programming in your terminal.',
    category: 'coding-cli',
    url: 'https://aider.chat',
    pricing: 'free',
    tags: ['cli', 'opensource', 'pair-programming'],
    used: false,
  },

  // === LANGUAGE MODELS ===
  {
    id: 'claude',
    name: 'Claude',
    description: 'Anthropic\'s AI assistant. Best for coding and reasoning.',
    category: 'llm',
    url: 'https://claude.ai',
    pricing: 'freemium',
    rating: 5,
    review: 'My main AI. Claude is the brain behind everything.',
    tags: ['chat', 'anthropic', 'reasoning'],
    hasAPI: true,
    used: true,
  },
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    description: 'OpenAI\'s GPT-4 powered assistant.',
    category: 'llm',
    url: 'https://chat.openai.com',
    pricing: 'freemium',
    rating: 4,
    tags: ['chat', 'openai', 'gpt4'],
    hasAPI: true,
    used: true,
  },
  {
    id: 'grok',
    name: 'Grok',
    description: 'xAI\'s unfiltered AI with real-time X data.',
    category: 'llm',
    url: 'https://grok.x.ai',
    pricing: 'paid',
    rating: 4,
    tags: ['chat', 'xai', 'twitter'],
    hasAPI: true,
    used: true,
  },
  {
    id: 'gemini',
    name: 'Gemini',
    description: 'Google\'s multimodal AI. Good for long context.',
    category: 'llm',
    url: 'https://gemini.google.com',
    pricing: 'freemium',
    rating: 4,
    tags: ['chat', 'google', 'multimodal'],
    hasAPI: true,
    used: true,
  },

  // === VIDEO CREATION ===
  {
    id: 'runway',
    name: 'Runway',
    description: 'Gen-3 Alpha video generation. Industry standard.',
    category: 'video',
    url: 'https://runwayml.com',
    pricing: 'paid',
    rating: 5,
    review: 'Best video AI right now. Gen-3 is insane.',
    tags: ['video', 'generation', 'editing'],
    hasAPI: true,
    used: true,
  },
  {
    id: 'sora',
    name: 'Sora',
    description: 'OpenAI\'s text-to-video model.',
    category: 'video',
    url: 'https://openai.com/sora',
    pricing: 'paid',
    tags: ['video', 'openai', 'generation'],
    hasAPI: false,
    used: false,
  },
  {
    id: 'veo',
    name: 'Veo (Google)',
    description: 'Google\'s video generation via Gemini.',
    category: 'video',
    url: 'https://deepmind.google/technologies/veo/',
    pricing: 'paid',
    rating: 4,
    tags: ['video', 'google', 'gemini'],
    hasAPI: true,
    used: true,
  },
  {
    id: 'kling',
    name: 'Kling',
    description: 'Kuaishou\'s video generation model.',
    category: 'video',
    url: 'https://klingai.com',
    pricing: 'freemium',
    tags: ['video', 'chinese', 'generation'],
    used: false,
  },
  {
    id: 'pika',
    name: 'Pika',
    description: 'AI video generation and editing.',
    category: 'video',
    url: 'https://pika.art',
    pricing: 'freemium',
    tags: ['video', 'generation'],
    used: false,
  },

  // === IMAGE GENERATION ===
  {
    id: 'midjourney',
    name: 'Midjourney',
    description: 'Best aesthetic image generation. Discord-based.',
    category: 'image',
    url: 'https://midjourney.com',
    pricing: 'paid',
    rating: 5,
    review: 'Still the king of aesthetics. Nothing beats MJ for quality.',
    tags: ['image', 'art', 'discord'],
    used: true,
  },
  {
    id: 'dalle',
    name: 'DALL-E 3',
    description: 'OpenAI\'s image generation in ChatGPT.',
    category: 'image',
    url: 'https://openai.com/dall-e-3',
    pricing: 'paid',
    rating: 4,
    tags: ['image', 'openai', 'chatgpt'],
    hasAPI: true,
    used: true,
  },
  {
    id: 'leonardo',
    name: 'Leonardo.ai',
    description: 'Phoenix model. Good for consistent characters.',
    category: 'image',
    url: 'https://leonardo.ai',
    pricing: 'freemium',
    rating: 4,
    tags: ['image', 'phoenix', 'characters'],
    hasAPI: true,
    used: true,
  },
  {
    id: 'imagen',
    name: 'Imagen 4',
    description: 'Google\'s image generation via Gemini API.',
    category: 'image',
    url: 'https://cloud.google.com/vertex-ai/docs/generative-ai/image/overview',
    pricing: 'paid',
    rating: 4,
    tags: ['image', 'google', 'api'],
    hasAPI: true,
    used: true,
  },
  {
    id: 'ideogram',
    name: 'Ideogram',
    description: 'Great for text in images and logos.',
    category: 'image',
    url: 'https://ideogram.ai',
    pricing: 'freemium',
    tags: ['image', 'text', 'logos'],
    used: false,
  },
  {
    id: 'flux',
    name: 'Flux',
    description: 'Black Forest Labs. Great open model.',
    category: 'image',
    url: 'https://blackforestlabs.ai',
    pricing: 'freemium',
    tags: ['image', 'opensource'],
    used: false,
  },

  // === VOICE & AUDIO ===
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'Best text-to-speech. Voice cloning. Emotions.',
    category: 'voice',
    url: 'https://elevenlabs.io',
    pricing: 'freemium',
    rating: 5,
    review: 'The voice standard. Nothing else comes close.',
    tags: ['tts', 'voice-cloning', 'emotions'],
    hasAPI: true,
    used: true,
  },
  {
    id: 'whisper',
    name: 'Whisper',
    description: 'OpenAI\'s speech-to-text. Best transcription.',
    category: 'voice',
    url: 'https://openai.com/whisper',
    pricing: 'freemium',
    rating: 5,
    review: 'Best transcription. Use it for everything.',
    tags: ['stt', 'transcription', 'openai'],
    hasAPI: true,
    used: true,
  },
  {
    id: 'openai-tts',
    name: 'OpenAI TTS',
    description: 'OpenAI\'s text-to-speech API.',
    category: 'voice',
    url: 'https://platform.openai.com/docs/guides/text-to-speech',
    pricing: 'paid',
    tags: ['tts', 'openai', 'api'],
    hasAPI: true,
    used: true,
  },

  // === MUSIC ===
  {
    id: 'suno',
    name: 'Suno',
    description: 'AI music generation. Full songs with vocals.',
    category: 'music',
    url: 'https://suno.ai',
    pricing: 'freemium',
    rating: 5,
    review: 'Mind-blowing music AI. Creates full songs.',
    tags: ['music', 'vocals', 'generation'],
    used: true,
  },
  {
    id: 'udio',
    name: 'Udio',
    description: 'AI music creation. Competitor to Suno.',
    category: 'music',
    url: 'https://udio.com',
    pricing: 'freemium',
    tags: ['music', 'vocals', 'generation'],
    used: false,
  },

  // === UX & DESIGN ===
  {
    id: 'v0',
    name: 'v0.dev',
    description: 'Vercel\'s AI UI generator. React/Next components.',
    category: 'design',
    url: 'https://v0.dev',
    pricing: 'freemium',
    rating: 5,
    review: 'Insane for quick UI. Just describe what you want.',
    tags: ['ui', 'react', 'vercel'],
    used: true,
  },
  {
    id: 'uxpilot',
    name: 'UX Pilot',
    description: 'AI-powered UX design tool.',
    category: 'design',
    url: 'https://uxpilot.ai',
    pricing: 'paid',
    tags: ['ux', 'design', 'figma'],
    used: true,
  },
  {
    id: 'bolt',
    name: 'Bolt.new',
    description: 'AI app builder. Full stack in browser.',
    category: 'design',
    url: 'https://bolt.new',
    pricing: 'freemium',
    tags: ['app-builder', 'fullstack'],
    used: true,
  },
  {
    id: 'lovable',
    name: 'Lovable',
    description: 'AI app builder with Supabase integration.',
    category: 'design',
    url: 'https://lovable.dev',
    pricing: 'freemium',
    tags: ['app-builder', 'supabase'],
    used: true,
  },
  {
    id: 'replit',
    name: 'Replit',
    description: 'AI-powered online IDE and deployment.',
    category: 'design',
    url: 'https://replit.com',
    pricing: 'freemium',
    tags: ['ide', 'deploy', 'ai-agent'],
    used: true,
  },

  // === APIs & INFRASTRUCTURE ===
  {
    id: 'openai-api',
    name: 'OpenAI API',
    description: 'GPT-4, DALL-E, Whisper, TTS all in one.',
    category: 'api',
    url: 'https://platform.openai.com',
    pricing: 'paid',
    rating: 5,
    tags: ['api', 'gpt', 'multimodal'],
    hasAPI: true,
    used: true,
  },
  {
    id: 'anthropic-api',
    name: 'Anthropic API',
    description: 'Claude API. Best for coding and reasoning.',
    category: 'api',
    url: 'https://console.anthropic.com',
    pricing: 'paid',
    rating: 5,
    tags: ['api', 'claude', 'reasoning'],
    hasAPI: true,
    used: true,
  },
  {
    id: 'gemini-api',
    name: 'Gemini API',
    description: 'Google\'s API. Vertex AI integration.',
    category: 'api',
    url: 'https://ai.google.dev',
    pricing: 'freemium',
    rating: 4,
    tags: ['api', 'google', 'multimodal'],
    hasAPI: true,
    used: true,
  },
  {
    id: 'vertex',
    name: 'Vertex AI',
    description: 'Google Cloud AI platform. Enterprise grade.',
    category: 'api',
    url: 'https://cloud.google.com/vertex-ai',
    pricing: 'paid',
    tags: ['api', 'google', 'enterprise'],
    hasAPI: true,
    used: true,
  },
  {
    id: 'replicate',
    name: 'Replicate',
    description: 'Run any open source model via API.',
    category: 'api',
    url: 'https://replicate.com',
    pricing: 'paid',
    tags: ['api', 'opensource', 'models'],
    hasAPI: true,
    used: true,
  },

  // === RESEARCH & SEARCH ===
  {
    id: 'perplexity',
    name: 'Perplexity',
    description: 'AI search engine. Real-time answers with sources.',
    category: 'research',
    url: 'https://perplexity.ai',
    pricing: 'freemium',
    rating: 5,
    review: 'Best for research. Always up to date.',
    tags: ['search', 'research', 'citations'],
    hasAPI: true,
    used: true,
  },

  // === DEPLOY & HOST ===
  {
    id: 'vercel',
    name: 'Vercel',
    description: 'Deploy Next.js and React. Best DX.',
    category: 'deploy',
    url: 'https://vercel.com',
    pricing: 'freemium',
    rating: 5,
    review: 'The gold standard for deployment.',
    tags: ['deploy', 'nextjs', 'edge'],
    used: true,
  },
  {
    id: 'supabase',
    name: 'Supabase',
    description: 'Postgres + Auth + Storage + Realtime.',
    category: 'deploy',
    url: 'https://supabase.com',
    pricing: 'freemium',
    rating: 5,
    review: 'Firebase killer. Backend in minutes.',
    tags: ['backend', 'postgres', 'auth'],
    used: true,
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    description: 'Edge computing, CDN, Workers, AI.',
    category: 'deploy',
    url: 'https://cloudflare.com',
    pricing: 'freemium',
    tags: ['cdn', 'edge', 'workers'],
    used: true,
  },
];

export function getToolsByCategory(categoryId: string): Tool[] {
  return tools.filter(t => t.category === categoryId);
}

export function getUsedTools(): Tool[] {
  return tools.filter(t => t.used);
}

export function getToolsWithAPI(): Tool[] {
  return tools.filter(t => t.hasAPI);
}
